create table comments
(
    id        bigint generated by default as identity primary key,
    parent_id bigint references comments (id) on delete cascade, -- ссылка на родителя
    content   text not null,                                     -- текст комментария
    created   timestamp with time zone default current_timestamp -- время создания
);

-- индекс для быстрого поиска детей конкретного родителя
create index idx_comments_parent_id on comments (parent_id);

-- индекс для текстового поиска
create index idx_comments_content on comments using gin (to_tsvector('russian', content));
